### ISSUE TITLE
Create Mock Up of UI

### ISSUE THREAD

**Issue by shaqqy** [shaqqy/School-project#1]
Create a Mock Up for the different "screens" of the UI

**Comment by shaqqy** [comment]
https://www.figma.com/file/NVvnuYxCJsoU5lBN6eMY48/free-game-ui-kit-(Community)?type=design&node-id=1%3A21&mode=design&t=hGnLiIef8oVW9kHX-1

**Comment by coding-adrian** [comment]
added screen shots of ui as mock up
